spring.application.name=taxonomia-api
server.port=8084

app.tree-strategy=custom
app.storage=mongo

spring.data.mongodb.uri=mongodb://localhost:27017/taxonomia
spring.data.mongodb.database=taxonomia

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  