DROP TABLE IF EXISTS nodes;

CREATE TABLE nodes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "value"     VARCHAR(255) NOT NULL,
    parent_id   BIGINT,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_nodes_parent FOREIGN KEY (parent_id) REFERENCES nodes(id) ON DELETE CASCADE
);

CREATE INDEX idx_nodes_parent_id ON nodes(parent_id);
