# ===============================================
#  SELECTORES - gestionados por Rol C-Carlos Ramos

# ===============================================
app.tree-strategy=collections
app.storage=mongo

# ===============================================
#  SERVIDOR
# ===============================================
server.port=8080

# ===============================================
#  MONGODB - Rol C
# ===============================================
spring.data.mongodb.uri=mongodb://localhost:27017/taxonomia
spring.data.mongodb.database=taxonomia

# ===============================================
#  POSTGRESQL - Rol B (pendiente)
# ===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/taxonomia
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

# ===============================================
#  EVITAR CONFLICTOS entre JPA y MongoDB
# ===============================================
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration