spring.application.name=taxonomia-api
server.port=8084

app.tree-strategy=custom
app.storage=memory

# Sin DataSource en perfil por defecto (memoria)
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration,\
  org.springframework.boot.autoconfigure.neo4j.Neo4jAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.neo4j.Neo4jDataAutoConfiguration

# Springdoc - evitar duplicados
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.override-with-generic-response=false
springdoc.writer-with-default-pretty-printer=true
springdoc.default-produces-media-type=application/json

# Esto evita que aparezca el grupo "tree Controller" automatico
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.show-actuator=false

# Actuator (health checks Docker / monitoreo)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true