openapi: 3.0.3

info:
  title: Taxonomía Biológica API
  version: 1.0.0
  description: API para gestionar un árbol de taxonomía biológica en memoria

servers:
  - url: http://localhost:8084

paths:

  /nodes/root:
    post:
      summary: Crear nodo raíz
      parameters:
        - name: value
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Nodo raíz creado

  /nodes/{parentId}/children:
    post:
      summary: Agregar nodo hijo
      parameters:
        - name: parentId
          in: path
          required: true
          schema:
            type: integer

        - name: value
          in: query
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Nodo hijo agregado

  /tree:
    get:
      summary: Obtener árbol completo
      responses:
        "200":
          description: Árbol completo en memoria